In [712]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [713]:
df=pd.read_excel(r"C:\Users\Ramapriya Murugesan\Desktop\Call centre Performance Analysis\Dataset\call_center .xlsx",header=None)

In [714]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,NaN,Call Centre Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating,NaN,NaN,NaN,Customer ID,Gedner,Age,City
3,NaN,Call_7271,C0003,116,R05,2023-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,C0001,Male,41,Columbus
4,NaN,Call_7272,C0004,119,R05,2023-01-01 00:00:00,135,2.9,NaN,NaN,NaN,C0002,Male,31,Cleveland

## Calls Table

In [715]:
calls=pd.read_excel(r"C:\Users\Ramapriya Murugesan\Desktop\Call centre Performance Analysis\Dataset\call_center .xlsx",header=2,usecols="B:H")

In [716]:
calls.head()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,Call_7271,C0003,116,R05,2023-01-01,NaN,NaN
1,Call_7272,C0004,119,R05,2023-01-01,135.0,2.9
2,Call_7273,C0005,68,R02,2023-01-01,66.0,4.7
3,Call_7274,C0014,119,R02,2023-01-01,22.0,2.9
4,Call_7275,C0011,128,R01,2023-01-02,31.0,2.8

## Customers Table

In [717]:
customer=pd.read_excel(r"C:\Users\Ramapriya Murugesan\Desktop\Call centre Performance Analysis\Dataset\call_center .xlsx",header=2,usecols="L:O",nrows=15)

In [718]:
customer

   Customer ID.1  Gedner  Age        City
0          C0001    Male   41    Columbus
1          C0002    Male   31   Cleveland
2          C0003    Male   26  Cincinnati
3          C0004    Male   36  Cincinnati
4          C0005    Male   37    Columbus
5          C0006    Male   23    Columbus
6          C0007  Female   22   Cleveland
7          C0008  Female   42   Cleveland
8          C0009  Female   25    Columbus
9          C0010  Female   30   Cleveland
10         C0011  Female   30  Cincinnati
11         C0012  Female   28  Cincinnati
12         C0013  Female   37   Cleveland
13         C0014  Female   38    Columbus
14         C0015  Female   43   Cleveland

In [719]:
customer.head()

  Customer ID.1 Gedner  Age        City
0         C0001   Male   41    Columbus
1         C0002   Male   31   Cleveland
2         C0003   Male   26  Cincinnati
3         C0004   Male   36  Cincinnati
4         C0005   Male   37    Columbus

In [720]:
calls.tail()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
995,Call_8266,C0002,81,R05,2023-12-30,28.0,3.9
996,Call_8267,C0007,127,R04,2023-12-30,215.0,3.8
997,Call_8268,C0013,146,R05,2023-12-31,115.0,2.3
998,Call_8269,C0010,123,R05,2023-12-31,64.0,3.7
999,Call_8270,C0009,114,R01,2023-12-31,40.0,3.9

In [721]:
customer.tail()

   Customer ID.1  Gedner  Age        City
10         C0011  Female   30  Cincinnati
11         C0012  Female   28  Cincinnati
12         C0013  Female   37   Cleveland
13         C0014  Female   38    Columbus
14         C0015  Female   43   Cleveland

In [722]:
calls.sample(10)

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
441,Call_7712,C0010,119,R01,2023-05-01,105.0,4.7
477,Call_7748,C0005,88,R04,2023-05-17,78.0,4.3
186,Call_7457,C0013,41,R04,2023-03-07,68.0,4.0
896,Call_8167,C0007,52,R02,2023-11-06,220.0,5.0
436,Call_7707,C0008,60,R02,2023-05-01,41.0,4.8
255,Call_7526,C0007,59,R01,2023-03-21,215.0,4.1
215,Call_7486,C0013,28,R02,2023-03-14,78.0,3.8
918,Call_8189,C0011,88,R05,2023-11-15,220.0,4.1
124,Call_7395,C0015,65,R05,2023-02-19,80.0,4.0
533,Call_7804,C0013,125,R05,2023-06-09,87.0,4.1

In [723]:
customer.sample(10)

   Customer ID.1  Gedner  Age        City
0          C0001    Male   41    Columbus
8          C0009  Female   25    Columbus
14         C0015  Female   43   Cleveland
9          C0010  Female   30   Cleveland
5          C0006    Male   23    Columbus
4          C0005    Male   37    Columbus
11         C0012  Female   28  Cincinnati
2          C0003    Male   26  Cincinnati
12         C0013  Female   37   Cleveland
3          C0004    Male   36  Cincinnati

In [724]:
type(calls)

pandas.core.frame.DataFrame

In [725]:
calls.shape

(1000, 7)

In [726]:
calls.columns

Index(['Call number', 'Customer ID', 'Duration', 'Representative',
       'Date of Call', 'Purchase Amount', 'Satisfaction Rating'],
      dtype='object')

In [727]:
calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Call number          1000 non-null   object
 1   Customer ID          1000 non-null   object
 2   Duration             1000 non-null   int64
 3   Representative       1000 non-null   object
 4   Date of Call         1000 non-null   datetime64[ns]
 5   Purchase Amount      999 non-null    float64
 6   Satisfaction Rating  997 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 54.8+ KB

In [728]:
calls.info

<bound method DataFrame.info of     Call number Customer ID  Duration Representative Date of Call  \
0     Call_7271       C0003       116            R05   2023-01-01
1     Call_7272       C0004       119            R05   2023-01-01
2     Call_7273       C0005        68            R02   2023-01-01
3     Call_7274       C0014       119            R02   2023-01-01
4     Call_7275       C0011       128            R01   2023-01-02
..          ...         ...       ...            ...          ...
995   Call_8266       C0002        81            R05   2023-12-30
996   Call_8267       C0007       127            R04   2023-12-30
997   Call_8268       C0013       146            R05   2023-12-31
998   Call_8269       C0010       123            R05   2023-12-31
999   Call_8270       C0009       114            R01   2023-12-31

     Purchase Amount  Satisfaction Rating
0                NaN                  NaN
1              135.0                  2.9
2               66.0                  4.7
3               22.0                  2.9
4               31.0                  2.8
..               ...                  ...
995             28.0                  3.9
996            215.0                  3.8
997            115.0                  2.3
998             64.0                  3.7
999             40.0                  3.9

[1000 rows x 7 columns]>

In [729]:
calls.describe()

,Duration,Date of Call,Purchase Amount,Satisfaction Rating
count,1000.000000,1000,999.000000,997.000000
mean,89.850000,2023-06-15 00:34:33.600000,96.591592,3.883651
min,2.000000,2023-01-01 00:00:00,20.000000,0.000000
25%,62.000000,2023-03-20 00:00:00,50.000000,3.400000
50%,89.000000,2023-05-25 12:00:00,88.000000,4.000000
75%,119.000000,2023-09-24 00:00:00,130.000000,4.500000
max,176.000000,2023-12-31 00:00:00,225.000000,5.000000
std,37.626736,NaN,52.482666,0.835521

In [730]:
calls.isnull()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False

In [731]:
calls.isnull().sum()

Call number            0
Customer ID            0
Duration               0
Representative         0
Date of Call           0
Purchase Amount        1
Satisfaction Rating    3
dtype: int64

In [732]:
calls.isnull().any()

Call number            False
Customer ID            False
Duration               False
Representative         False
Date of Call           False
Purchase Amount         True
Satisfaction Rating     True
dtype: bool

In [733]:
calls.isnull().all()

Call number            False
Customer ID            False
Duration               False
Representative         False
Date of Call           False
Purchase Amount        False
Satisfaction Rating    False
dtype: bool

In [734]:
calls.isnull().any(axis=1)  #Rows

0       True
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [735]:
calls.isnull().any(axis=0) #column

Call number            False
Customer ID            False
Duration               False
Representative         False
Date of Call           False
Purchase Amount         True
Satisfaction Rating     True
dtype: bool

In [736]:
calls[calls.isnull().any(axis=1) ]

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,Call_7271,C0003,116,R05,2023-01-01,NaN,NaN
8,Call_7279,C0005,31,R02,2023-01-03,135.0,NaN
14,Call_7285,C0013,48,R01,2023-01-04,68.0,NaN

In [737]:
customer.isnull().sum()

Customer ID.1    0
Gedner           0
Age              0
City             0
dtype: int64

## Handle Missing Values

In [738]:
calls["Purchase Amount"]

0        NaN
1      135.0
2       66.0
3       22.0
4       31.0
       ...
995     28.0
996    215.0
997    115.0
998     64.0
999     40.0
Name: Purchase Amount, Length: 1000, dtype: float64

In [739]:
#calls['Purchase Amount']=calls["Purchase Amount"].fillna(calls["Purchase Amount"].mean(),inplace=True)

In [740]:
calls.isnull().sum()

Call number            0
Customer ID            0
Duration               0
Representative         0
Date of Call           0
Purchase Amount        1
Satisfaction Rating    3
dtype: int64

In [741]:
#calls["Representative"]=calls["Representative"].fillna("unknown",inplace=True)

In [742]:
calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Call number          1000 non-null   object
 1   Customer ID          1000 non-null   object
 2   Duration             1000 non-null   int64
 3   Representative       1000 non-null   object
 4   Date of Call         1000 non-null   datetime64[ns]
 5   Purchase Amount      999 non-null    float64
 6   Satisfaction Rating  997 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 54.8+ KB

In [743]:
calls.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [744]:
calls.duplicated().sum()

np.int64(0)

In [745]:
calls.drop_duplicates().all()

C:\Users\Ramapriya Murugesan\AppData\Local\Temp\ipykernel_12680\2427564813.py:1: FutureWarning: 'all' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).all() instead.
  calls.drop_duplicates().all()

Call number             True
Customer ID             True
Duration                True
Representative          True
Date of Call            True
Purchase Amount         True
Satisfaction Rating    False
dtype: bool

In [746]:
calls.drop_duplicates().all(axis=1)

C:\Users\Ramapriya Murugesan\AppData\Local\Temp\ipykernel_12680\555831959.py:1: FutureWarning: 'all' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).all() instead.
  calls.drop_duplicates().all(axis=1)

0      True
1      True
2      True
3      True
4      True
       ...
995    True
996    True
997    True
998    True
999    True
Length: 1000, dtype: bool

In [747]:
calls.drop_duplicates().all(axis=1).sum()

C:\Users\Ramapriya Murugesan\AppData\Local\Temp\ipykernel_12680\2433151174.py:1: FutureWarning: 'all' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).all() instead.
  calls.drop_duplicates().all(axis=1).sum()

np.int64(999)

In [748]:
calls[calls.duplicated()]

Empty DataFrame
Columns: [Call number, Customer ID, Duration, Representative, Date of Call, Purchase Amount, Satisfaction Rating]
Index: []

In [749]:
calls.drop_duplicates(inplace=True)

In [750]:
calls["Date of Call"]=pd.to_datetime(calls["Date of Call"])

In [751]:
calls.dtypes

Call number                    object
Customer ID                    object
Duration                        int64
Representative                 object
Date of Call           datetime64[ns]
Purchase Amount               float64
Satisfaction Rating           float64
dtype: object

In [752]:
calls.columns

Index(['Call number', 'Customer ID', 'Duration', 'Representative',
       'Date of Call', 'Purchase Amount', 'Satisfaction Rating'],
      dtype='object')

In [753]:
calls.rename(columns={"Purchase Amount":"purchase","Satisfaction Rating":"Rating"},inplace=True)

In [754]:
calls.columns

Index(['Call number', 'Customer ID', 'Duration', 'Representative',
       'Date of Call', 'purchase', 'Rating'],
      dtype='object')

In [755]:
calls.to_csv("Cleaned_data.csv",index=False)

In [756]:
type(calls["Customer ID"])

pandas.core.series.Series

In [757]:
calls[["purchase","Representative"]]

     purchase Representative
0         NaN            R05
1       135.0            R05
2        66.0            R02
3        22.0            R02
4        31.0            R01
..        ...            ...
995      28.0            R05
996     215.0            R04
997     115.0            R05
998      64.0            R05
999      40.0            R01

[1000 rows x 2 columns]

In [758]:
calls.Rating[calls["Rating"]<10]

1      2.9
2      4.7
3      2.9
4      2.8
5      4.8
      ...
995    3.9
996    3.8
997    2.3
998    3.7
999    3.9
Name: Rating, Length: 997, dtype: float64

In [759]:
calls.Rating.sort_values()

69     0.0
445    0.7
180    0.7
557    0.9
128    1.0
      ...
20     5.0
32     5.0
0      NaN
8      NaN
14     NaN
Name: Rating, Length: 1000, dtype: float64

In [760]:
calls.Rating.sort_values(ascending=False)

33     5.0
940    5.0
577    5.0
759    5.0
254    5.0
      ...
445    0.7
69     0.0
0      NaN
8      NaN
14     NaN
Name: Rating, Length: 1000, dtype: float64

In [761]:
calls.Representative.unique()

array(['R05', 'R02', 'R01', 'R04', 'R03'], dtype=object)

In [762]:
customer.City.unique()

array(['Columbus', 'Cleveland', 'Cincinnati'], dtype=object)

In [763]:
calls.Representative.value_counts()

Representative
R02    218
R03    207
R05    200
R01    189
R04    186
Name: count, dtype: int64

In [764]:
type(calls.Representative.value_counts())

pandas.core.series.Series

In [765]:
calls.Representative.value_counts()

Representative
R02    218
R03    207
R05    200
R01    189
R04    186
Name: count, dtype: int64

In [766]:
repcount=calls.Representative.value_counts()
print(repcount.max())

218

In [767]:
calls.groupby("Representative")["Rating"].mean()
print(repcount)

Representative
R02    218
R03    207
R05    200
R01    189
R04    186
Name: count, dtype: int64

In [768]:
high=calls.groupby("Representative")["Call number"].count()
high.max()

218

## Merge

In [776]:
merge_table=pd.merge(calls,customer,left_on="Customer ID",right_on="Customer ID.1")

In [777]:
print(merge_table.head())

  Call number Customer ID  Duration Representative Date of Call  purchase  \
0   Call_7271       C0003       116            R05   2023-01-01       NaN
1   Call_7272       C0004       119            R05   2023-01-01     135.0
2   Call_7273       C0005        68            R02   2023-01-01      66.0
3   Call_7274       C0014       119            R02   2023-01-01      22.0
4   Call_7275       C0011       128            R01   2023-01-02      31.0

   Rating Customer ID.1  Gedner  Age        City
0     NaN         C0003    Male   26  Cincinnati
1     2.9         C0004    Male   36  Cincinnati
2     4.7         C0005    Male   37    Columbus
3     2.9         C0014  Female   38    Columbus
4     2.8         C0011  Female   30  Cincinnati

In [779]:
merge_table.groupby("City")["purchase"].sum()

City
Cincinnati    25933.0
Cleveland     37849.0
Columbus      32713.0
Name: purchase, dtype: float64