In [579]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [580]:
df=pd.read_excel(r"C:\Users\Ramapriya Murugesan\Desktop\Call centre Performance Analysis\Dataset\call_center .xlsx",header=None)

In [581]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,NaN,Call Centre Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating,NaN,NaN,NaN,Customer ID,Gedner,Age,City
3,NaN,Call_7271,C0003,116,R05,2023-01-01 00:00:00,NaN,NaN,NaN,NaN,NaN,C0001,Male,41,Columbus
4,NaN,Call_7272,C0004,119,R05,2023-01-01 00:00:00,135,2.9,NaN,NaN,NaN,C0002,Male,31,Cleveland

## Calls Table

In [582]:
calls=pd.read_excel(r"C:\Users\Ramapriya Murugesan\Desktop\Call centre Performance Analysis\Dataset\call_center .xlsx",header=2,usecols="B:H")

In [583]:
calls.head()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,Call_7271,C0003,116,R05,2023-01-01,NaN,NaN
1,Call_7272,C0004,119,R05,2023-01-01,135.0,2.9
2,Call_7273,C0005,68,R02,2023-01-01,66.0,4.7
3,Call_7274,C0014,119,R02,2023-01-01,22.0,2.9
4,Call_7275,C0011,128,R01,2023-01-02,31.0,2.8

## Customers Table

In [584]:
customer=pd.read_excel(r"C:\Users\Ramapriya Murugesan\Desktop\Call centre Performance Analysis\Dataset\call_center .xlsx",header=2,usecols="L:O",nrows=15)

In [585]:
customer

   Customer ID.1  Gedner  Age        City
0          C0001    Male   41    Columbus
1          C0002    Male   31   Cleveland
2          C0003    Male   26  Cincinnati
3          C0004    Male   36  Cincinnati
4          C0005    Male   37    Columbus
5          C0006    Male   23    Columbus
6          C0007  Female   22   Cleveland
7          C0008  Female   42   Cleveland
8          C0009  Female   25    Columbus
9          C0010  Female   30   Cleveland
10         C0011  Female   30  Cincinnati
11         C0012  Female   28  Cincinnati
12         C0013  Female   37   Cleveland
13         C0014  Female   38    Columbus
14         C0015  Female   43   Cleveland

In [586]:
customer.head()

  Customer ID.1 Gedner  Age        City
0         C0001   Male   41    Columbus
1         C0002   Male   31   Cleveland
2         C0003   Male   26  Cincinnati
3         C0004   Male   36  Cincinnati
4         C0005   Male   37    Columbus

In [587]:
calls.tail()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
995,Call_8266,C0002,81,R05,2023-12-30,28.0,3.9
996,Call_8267,C0007,127,R04,2023-12-30,215.0,3.8
997,Call_8268,C0013,146,R05,2023-12-31,115.0,2.3
998,Call_8269,C0010,123,R05,2023-12-31,64.0,3.7
999,Call_8270,C0009,114,R01,2023-12-31,40.0,3.9

In [588]:
customer.tail()

   Customer ID.1  Gedner  Age        City
10         C0011  Female   30  Cincinnati
11         C0012  Female   28  Cincinnati
12         C0013  Female   37   Cleveland
13         C0014  Female   38    Columbus
14         C0015  Female   43   Cleveland

In [589]:
calls.sample(10)

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
747,Call_8018,C0011,96,R05,2023-09-23,80.0,3.6
825,Call_8096,C0005,139,R02,2023-10-13,48.0,4.7
692,Call_7963,C0011,49,R04,2023-08-27,105.0,3.3
700,Call_7971,C0013,124,R05,2023-09-01,132.0,4.0
193,Call_7464,C0007,85,R04,2023-03-10,46.0,4.9
971,Call_8242,C0002,141,R05,2023-12-16,66.0,3.2
267,Call_7538,C0012,142,R04,2023-03-24,31.0,4.4
459,Call_7730,C0009,25,R01,2023-05-08,52.0,3.8
128,Call_7399,C0007,130,R04,2023-02-21,150.0,1.0
60,Call_7331,C0013,74,R01,2023-01-24,66.0,4.0

In [590]:
customer.sample(10)

   Customer ID.1  Gedner  Age        City
10         C0011  Female   30  Cincinnati
5          C0006    Male   23    Columbus
8          C0009  Female   25    Columbus
12         C0013  Female   37   Cleveland
11         C0012  Female   28  Cincinnati
0          C0001    Male   41    Columbus
2          C0003    Male   26  Cincinnati
7          C0008  Female   42   Cleveland
9          C0010  Female   30   Cleveland
1          C0002    Male   31   Cleveland

In [591]:
type(calls)

pandas.core.frame.DataFrame

In [592]:
calls.shape

(1000, 7)

In [593]:
calls.columns

Index(['Call number', 'Customer ID', 'Duration', 'Representative',
       'Date of Call', 'Purchase Amount', 'Satisfaction Rating'],
      dtype='object')

In [594]:
calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Call number          1000 non-null   object
 1   Customer ID          1000 non-null   object
 2   Duration             1000 non-null   int64
 3   Representative       1000 non-null   object
 4   Date of Call         1000 non-null   datetime64[ns]
 5   Purchase Amount      999 non-null    float64
 6   Satisfaction Rating  997 non-null    float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 54.8+ KB

In [595]:
calls.info

<bound method DataFrame.info of     Call number Customer ID  Duration Representative Date of Call  \
0     Call_7271       C0003       116            R05   2023-01-01
1     Call_7272       C0004       119            R05   2023-01-01
2     Call_7273       C0005        68            R02   2023-01-01
3     Call_7274       C0014       119            R02   2023-01-01
4     Call_7275       C0011       128            R01   2023-01-02
..          ...         ...       ...            ...          ...
995   Call_8266       C0002        81            R05   2023-12-30
996   Call_8267       C0007       127            R04   2023-12-30
997   Call_8268       C0013       146            R05   2023-12-31
998   Call_8269       C0010       123            R05   2023-12-31
999   Call_8270       C0009       114            R01   2023-12-31

     Purchase Amount  Satisfaction Rating
0                NaN                  NaN
1              135.0                  2.9
2               66.0                  4.7
3               22.0                  2.9
4               31.0                  2.8
..               ...                  ...
995             28.0                  3.9
996            215.0                  3.8
997            115.0                  2.3
998             64.0                  3.7
999             40.0                  3.9

[1000 rows x 7 columns]>

In [596]:
calls.describe()

,Duration,Date of Call,Purchase Amount,Satisfaction Rating
count,1000.000000,1000,999.000000,997.000000
mean,89.850000,2023-06-15 00:34:33.600000,96.591592,3.883651
min,2.000000,2023-01-01 00:00:00,20.000000,0.000000
25%,62.000000,2023-03-20 00:00:00,50.000000,3.400000
50%,89.000000,2023-05-25 12:00:00,88.000000,4.000000
75%,119.000000,2023-09-24 00:00:00,130.000000,4.500000
max,176.000000,2023-12-31 00:00:00,225.000000,5.000000
std,37.626736,NaN,52.482666,0.835521

In [597]:
calls.isnull()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False

In [598]:
calls.isnull().sum()

Call number            0
Customer ID            0
Duration               0
Representative         0
Date of Call           0
Purchase Amount        1
Satisfaction Rating    3
dtype: int64

In [599]:
calls.isnull().any()

Call number            False
Customer ID            False
Duration               False
Representative         False
Date of Call           False
Purchase Amount         True
Satisfaction Rating     True
dtype: bool

In [600]:
calls.isnull().all()

Call number            False
Customer ID            False
Duration               False
Representative         False
Date of Call           False
Purchase Amount        False
Satisfaction Rating    False
dtype: bool

In [601]:
calls.isnull().any(axis=1)  #Rows

0       True
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [602]:
calls.isnull().any(axis=0) #column

Call number            False
Customer ID            False
Duration               False
Representative         False
Date of Call           False
Purchase Amount         True
Satisfaction Rating     True
dtype: bool

In [603]:
calls[calls.isnull().any(axis=1) ]

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,Call_7271,C0003,116,R05,2023-01-01,NaN,NaN
8,Call_7279,C0005,31,R02,2023-01-03,135.0,NaN
14,Call_7285,C0013,48,R01,2023-01-04,68.0,NaN

In [604]:
customer.isnull().sum()

Customer ID.1    0
Gedner           0
Age              0
City             0
dtype: int64

## Handle Missing Values

In [605]:
calls["Purchase Amount"]

0        NaN
1      135.0
2       66.0
3       22.0
4       31.0
       ...
995     28.0
996    215.0
997    115.0
998     64.0
999     40.0
Name: Purchase Amount, Length: 1000, dtype: float64

In [606]:
calls['Purchase Amount']=calls["Purchase Amount"].fillna(calls["Purchase Amount"].mean(),inplace=True)

In [607]:
calls.isnull().sum()

Call number               0
Customer ID               0
Duration                  0
Representative            0
Date of Call              0
Purchase Amount        1000
Satisfaction Rating       3
dtype: int64

In [608]:
calls["Representative"]=calls["Representative"].fillna("unknown",inplace=True)

C:\Users\Ramapriya Murugesan\AppData\Local\Temp\ipykernel_12680\1471799949.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  calls["Representative"]=calls["Representative"].fillna("unknown",inplace=True)

In [609]:
calls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Call number          1000 non-null   object
 1   Customer ID          1000 non-null   object
 2   Duration             1000 non-null   int64
 3   Representative       0 non-null      object
 4   Date of Call         1000 non-null   datetime64[ns]
 5   Purchase Amount      0 non-null      object
 6   Satisfaction Rating  997 non-null    float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 54.8+ KB

In [610]:
calls.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [611]:
calls.duplicated().sum()

np.int64(0)

In [612]:
calls.drop_duplicates().all()

C:\Users\Ramapriya Murugesan\AppData\Local\Temp\ipykernel_12680\2427564813.py:1: FutureWarning: 'all' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).all() instead.
  calls.drop_duplicates().all()

Call number             True
Customer ID             True
Duration                True
Representative          True
Date of Call            True
Purchase Amount         True
Satisfaction Rating    False
dtype: bool

In [613]:
calls.drop_duplicates().all(axis=1)

C:\Users\Ramapriya Murugesan\AppData\Local\Temp\ipykernel_12680\555831959.py:1: FutureWarning: 'all' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).all() instead.
  calls.drop_duplicates().all(axis=1)

0      True
1      True
2      True
3      True
4      True
       ...
995    True
996    True
997    True
998    True
999    True
Length: 1000, dtype: bool

In [614]:
calls.drop_duplicates().all(axis=1).sum()

C:\Users\Ramapriya Murugesan\AppData\Local\Temp\ipykernel_12680\2433151174.py:1: FutureWarning: 'all' with datetime64 dtypes is deprecated and will raise in a future version. Use (obj != pd.Timestamp(0)).all() instead.
  calls.drop_duplicates().all(axis=1).sum()

np.int64(999)

In [615]:
calls[calls.duplicated()]

Empty DataFrame
Columns: [Call number, Customer ID, Duration, Representative, Date of Call, Purchase Amount, Satisfaction Rating]
Index: []

In [616]:
calls.drop_duplicates(inplace=True)

In [617]:
calls["Date of Call"]=pd.to_datetime(calls["Date of Call"])

In [618]:
calls.dtypes

Call number                    object
Customer ID                    object
Duration                        int64
Representative                 object
Date of Call           datetime64[ns]
Purchase Amount                object
Satisfaction Rating           float64
dtype: object

In [619]:
calls.columns

Index(['Call number', 'Customer ID', 'Duration', 'Representative',
       'Date of Call', 'Purchase Amount', 'Satisfaction Rating'],
      dtype='object')

In [620]:
calls.rename(columns={"Purchase Amount":"purchase","Satisfaction Rating":"Rating"},inplace=True)

In [621]:
calls.columns

Index(['Call number', 'Customer ID', 'Duration', 'Representative',
       'Date of Call', 'purchase', 'Rating'],
      dtype='object')

In [622]:
calls.to_csv("Cleaned_data.csv",index=False)

In [623]:
type(calls["Customer ID"])

pandas.core.series.Series

In [624]:
calls[["purchase","Representative"]]

    purchase Representative
0       None           None
1       None           None
2       None           None
3       None           None
4       None           None
..       ...            ...
995     None           None
996     None           None
997     None           None
998     None           None
999     None           None

[1000 rows x 2 columns]

In [629]:
calls.Rating[calls["Rating"]<10]

1      2.9
2      4.7
3      2.9
4      2.8
5      4.8
      ...
995    3.9
996    3.8
997    2.3
998    3.7
999    3.9
Name: Rating, Length: 997, dtype: float64

In [632]:
calls.Rating.sort_values()

69     0.0
445    0.7
180    0.7
557    0.9
128    1.0
      ...
20     5.0
32     5.0
0      NaN
8      NaN
14     NaN
Name: Rating, Length: 1000, dtype: float64

In [633]:
calls.Rating.sort_values(ascending=False)

33     5.0
940    5.0
577    5.0
759    5.0
254    5.0
      ...
445    0.7
69     0.0
0      NaN
8      NaN
14     NaN
Name: Rating, Length: 1000, dtype: float64